#!/bin/sh

NMPRC_FILE=".npmrc";
GITLAB_URL='your-gitlab-instance-host/api/v4/projects';
# init
echo "# [info] this file has been generated by '.scripts/init-npmrc-file.sh' script" >  $NMPRC_FILE;
# get '@your-group-name/your-npm-lib1' lib.
echo "# registery to get '@your-group-name/your-npm-lib1' library"                   >> $NMPRC_FILE;
echo "@your-group-name/your-npm-lib2:registry=https://$GITLAB_URL/18/packages/npm/"  >> $NMPRC_FILE;
echo "//$GITLAB_URL/42/packages/npm/:_authToken=\${CI_JOB_TOKEN}"                    >> $NMPRC_FILE;
# get '@your-group-name/your-npm-lib2' lib.
echo "# registery to get '@your-group-name/your-npm-lib2' library"                   >> $NMPRC_FILE;
echo "@your-group-name/your-npm-lib2:registry=https://$GITLAB_URL/17/packages/npm/"  >> $NMPRC_FILE;
echo "//$GITLAB_URL/66/packages/npm/:_authToken=\${CI_JOB_TOKEN}"                    >> $NMPRC_FILE;

exit 0;
