#!/bin/sh

NMPRC_FILE=".npmrc";
GITLAB_URL='your-gitlab-instance-host/api/v4/projects';
# init
echo "# [info] this file has been generated by '.scripts/init-npmrc-file.sh' script"     >  $NMPRC_FILE;
# configure a publication registery to publish this project as a npm library.
echo "# registery to publish created lib."                                               >> $NMPRC_FILE;
echo "@your-group-name:registry=https://$GITLAB_URL/\${CI_PROJECT_ID}/packages/npm/"     >> $NMPRC_FILE;
echo "//$GITLAB_URL/\${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"         >> $NMPRC_FILE;

exit 0;
